local fzf = require("fzf-lua")
vim.keymap.set('n', '<leader>ff', fzf.files, {})
vim.keymap.set('n', '<leader>fg', fzf.live_grep, {})
vim.keymap.set('n', '<leader>fb', fzf.buffers, {})
vim.keymap.set('n', '<leader>fh', fzf.helptags, {})
vim.keymap.set('n', '<leader>fc', function () fzf.files({ cwd = '~/.config/nvim' }) end, {})
vim.keymap.set('n', '<leader>fm', fzf.marks, {})
vim.keymap.set('n', '<leader>fr', fzf.resume, {})
vim.keymap.set('n', 'gri', fzf.lsp_implementations)
vim.keymap.set('n', 'grd', fzf.lsp_definitions)
vim.keymap.set('n', 'grr', fzf.lsp_references)

fzf.register_ui_select()
